import React from 'react';
import { Shield } from 'lucide-react';

const KadenTerms = () => {
  return (
    <main className="page-container fade-in">
      <div style={{ display: 'flex', alignItems: 'center', gap: '1rem', marginBottom: '2rem' }}>
        <Shield size={48} color="#6366F1" />
        <h1 style={{ margin: 0 }}>Terms of Use</h1>
      </div>

      <p><strong>Kaden mobile app</strong> · Last updated: September 4, 2026 · Effective: September 4, 2026</p>

      <p>These terms are an agreement between you and Hasan Can Selmo, Istanbul, Turkey (“we”, “us”) about your use of the Kaden mobile app. By downloading or using Kaden you accept them. If you do not accept them, do not use the app.</p>

      <h2>1. What Kaden is</h2>
      <p>Kaden is a 30-day self-improvement program about conversation and social skills. It gives you a short lesson or exercise each day, a small number of conversation exams with an AI character, occasional real-world tasks, and a feature called Second Eye that suggests replies for a conversation you are stuck in.</p>
      <p>Kaden is educational content. It is not a medical, psychological, psychiatric, therapeutic or counselling service, and it is not a substitute for one. The word “diagnosis” in the app is a metaphor for a repeated pattern in your own answers — it is not a clinical diagnosis. If you are struggling with something serious, please speak to a qualified professional.</p>
      <p>Kaden is not a dating service or a matching service, and we do not promise any particular result, relationship, or outcome.</p>

      <h2>2. Who may use it</h2>
      <p>You must be at least 13 years old and legally able to enter into this agreement. You may not use Kaden on behalf of anyone else.</p>

      <h2>3. Your anonymous account</h2>
      <p>Kaden has no sign-up. The app creates an anonymous identity on your device and keeps your progress under it. This means:</p>
      <ul>
        <li>we cannot recover your progress for you, because we cannot tell which record is yours;</li>
        <li>if you delete the app, reset your device or use the in-app deletion, that progress may be lost permanently; and</li>
        <li>anyone with access to your unlocked device can see what you have written in the app.</li>
      </ul>

      <h2>4. Subscriptions, billing and cancellation</h2>
      <p>The diagnosis is free. The rest of the program requires an auto-renewing subscription. Two are offered, and both unlock the same content:</p>
      <ul>
        <li>1 week — renews weekly.</li>
        <li>3 months — renews every three months.</li>
      </ul>
      <p>There is no free trial.</p>
      <ul>
        <li>The price shown in the app is the price your store charges in your local currency, including any applicable taxes. Prices may differ by country and may change; a change will never apply to a period you have already paid for.</li>
        <li>Payment is charged to your Apple ID or Google Play account when you confirm the purchase.</li>
        <li>Your subscription renews automatically unless you cancel it at least 24 hours before the end of the current period. Your account is charged for renewal within 24 hours before the period ends.</li>
        <li>You can manage or cancel your subscription in your store account settings (Settings → Subscription → Manage subscription in the app links there). Deleting the app does not cancel the subscription.</li>
        <li>Refunds are handled by Apple or Google under their own policies, not by us. We cannot issue a refund for a store purchase, but we will help you make the request.</li>
        <li>Purchases are tied to your store account. Use Restore purchase in the app to unlock the program on another device with the same store account.</li>
        <li>Where consumer law gives you a right of withdrawal, that right applies to the store transaction and is exercised through Apple or Google.</li>
      </ul>

      <h2>5. AI-generated content</h2>
      <p>Parts of Kaden are generated by an AI model. You must read them as suggestions, not instructions.</p>
      <ul>
        <li>Output can be inaccurate, generic, badly judged or unsuitable for the person you are talking to. You are responsible for anything you choose to send to a real person.</li>
        <li>Do not rely on AI output for any decision with legal, financial, medical or safety consequences.</li>
        <li>Safety filters are enabled, but no filter is perfect. If something offensive or harmful reaches you, report it from Settings → Support → Report an offensive suggestion and we will look at it.</li>
      </ul>

      <h2>6. What you may not do</h2>
      <p>Kaden is for improving your own conversations. You may not use it:</p>
      <ul>
        <li>to harass, stalk, intimidate, coerce, deceive, manipulate or pressure anyone;</li>
        <li>to pursue contact with someone who has asked you to stop, or with a minor;</li>
        <li>to generate sexual content involving minors, or content that is hateful, threatening or unlawful;</li>
        <li>to upload screenshots or other people’s personal data that you have no right to share;</li>
        <li>to impersonate anyone, or to build a profile of a specific person;</li>
        <li>to reverse engineer, decompile, scrape, resell, sublicense or redistribute the app or its content, or to bypass its paywall or security checks; or</li>
        <li>in any way that breaks the law where you live.</li>
      </ul>
      <p>We may suspend or end your access if you use Kaden this way.</p>

      <h2>7. Content and ownership</h2>
      <p>The program, its lessons, scenarios, exercises, text, design and code belong to us or our licensors and are protected by copyright. Your subscription gives you a personal, non-transferable, non-exclusive right to use them inside the app while it is active. It does not let you republish or sell them.</p>
      <p>What you write in the app stays yours. You grant us the limited right to store it and to send it for processing so we can provide the features you used — nothing more. We do not use your content to train our own models. See the Privacy Policy.</p>

      <h2>8. Availability</h2>
      <p>We try to keep Kaden working, but we do not promise it will be uninterrupted or error-free. AI features depend on third-party services and may be unavailable; when they are, the app falls back to pre-written content. We may change, suspend or discontinue features. If we discontinue the app entirely, we will not charge for a period you cannot use.</p>

      <h2>9. Disclaimers</h2>
      <p>To the fullest extent permitted by law, Kaden is provided “as is” and “as available”, without warranties of any kind, express or implied, including fitness for a particular purpose, accuracy, or that use of the app will produce any specific outcome in your social or personal life.</p>
      <p>Nothing in these terms limits rights you have under mandatory consumer law in your country.</p>

      <h2>10. Limitation of liability</h2>
      <p>To the fullest extent permitted by law, we are not liable for indirect, incidental, special or consequential damages, or for loss of data, opportunity or reputation, arising from your use of Kaden. Our total liability to you for any claim is limited to the amount you paid us for the app in the twelve months before the claim.</p>
      <p>This does not exclude liability for death or personal injury caused by negligence, for fraud, or for anything else that cannot be excluded by law.</p>

      <h2>11. Ending this agreement</h2>
      <p>You can stop at any time: cancel the subscription in your store account and delete the app. You can erase your data from Settings → Your data → Delete my data. We may end your access if you materially breach these terms.</p>

      <h2>12. Apple and Google</h2>
      <p>This agreement is between you and us, not with Apple or Google. They are not responsible for the app or its content, and they have no obligation to provide support for it. Apple and its subsidiaries are third-party beneficiaries of these terms and may enforce them against you. If the app fails to conform to any applicable warranty, you may notify Apple, and Apple will refund the purchase price; to the maximum extent permitted by law, Apple has no other warranty obligation with respect to the app.</p>

      <h2>13. Changes to these terms</h2>
      <p>We may update these terms. The date at the top will change, and if the update is significant we will surface it in the app. Continuing to use Kaden after an update means you accept it.</p>

      <h2>14. Governing law</h2>
      <p>These terms are governed by the laws of Turkey, and disputes will be heard by the courts of Istanbul, without affecting any right you have to bring a claim in the courts of the country where you live.</p>

      <h2>15. Contact</h2>
      <p>Hasan Can Selmo, Istanbul, Turkey · hasancanselmo07@gmail.com</p>

    </main>
  );
};

export default KadenTerms;
